/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TreeRouteImport } from './routes/tree'
import { Route as SuttaRouteImport } from './routes/sutta'
import { Route as ReflectRouteImport } from './routes/reflect'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ComicRouteImport } from './routes/comic'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SuttaSuttaIdRouteImport } from './routes/sutta.$suttaId'
import { Route as ReflectThinkingRouteImport } from './routes/reflect.thinking'
import { Route as ReflectAnswerRouteImport } from './routes/reflect.answer'

const TreeRoute = TreeRouteImport.update({
  id: '/tree',
  path: '/tree',
  getParentRoute: () => rootRouteImport,
} as any)
const SuttaRoute = SuttaRouteImport.update({
  id: '/sutta',
  path: '/sutta',
  getParentRoute: () => rootRouteImport,
} as any)
const ReflectRoute = ReflectRouteImport.update({
  id: '/reflect',
  path: '/reflect',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ComicRoute = ComicRouteImport.update({
  id: '/comic',
  path: '/comic',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuttaSuttaIdRoute = SuttaSuttaIdRouteImport.update({
  id: '/$suttaId',
  path: '/$suttaId',
  getParentRoute: () => SuttaRoute,
} as any)
const ReflectThinkingRoute = ReflectThinkingRouteImport.update({
  id: '/thinking',
  path: '/thinking',
  getParentRoute: () => ReflectRoute,
} as any)
const ReflectAnswerRoute = ReflectAnswerRouteImport.update({
  id: '/answer',
  path: '/answer',
  getParentRoute: () => ReflectRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/comic': typeof ComicRoute
  '/profile': typeof ProfileRoute
  '/reflect': typeof ReflectRouteWithChildren
  '/sutta': typeof SuttaRouteWithChildren
  '/tree': typeof TreeRoute
  '/reflect/answer': typeof ReflectAnswerRoute
  '/reflect/thinking': typeof ReflectThinkingRoute
  '/sutta/$suttaId': typeof SuttaSuttaIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/comic': typeof ComicRoute
  '/profile': typeof ProfileRoute
  '/reflect': typeof ReflectRouteWithChildren
  '/sutta': typeof SuttaRouteWithChildren
  '/tree': typeof TreeRoute
  '/reflect/answer': typeof ReflectAnswerRoute
  '/reflect/thinking': typeof ReflectThinkingRoute
  '/sutta/$suttaId': typeof SuttaSuttaIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/comic': typeof ComicRoute
  '/profile': typeof ProfileRoute
  '/reflect': typeof ReflectRouteWithChildren
  '/sutta': typeof SuttaRouteWithChildren
  '/tree': typeof TreeRoute
  '/reflect/answer': typeof ReflectAnswerRoute
  '/reflect/thinking': typeof ReflectThinkingRoute
  '/sutta/$suttaId': typeof SuttaSuttaIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/browse'
    | '/comic'
    | '/profile'
    | '/reflect'
    | '/sutta'
    | '/tree'
    | '/reflect/answer'
    | '/reflect/thinking'
    | '/sutta/$suttaId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/browse'
    | '/comic'
    | '/profile'
    | '/reflect'
    | '/sutta'
    | '/tree'
    | '/reflect/answer'
    | '/reflect/thinking'
    | '/sutta/$suttaId'
  id:
    | '__root__'
    | '/'
    | '/browse'
    | '/comic'
    | '/profile'
    | '/reflect'
    | '/sutta'
    | '/tree'
    | '/reflect/answer'
    | '/reflect/thinking'
    | '/sutta/$suttaId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrowseRoute: typeof BrowseRoute
  ComicRoute: typeof ComicRoute
  ProfileRoute: typeof ProfileRoute
  ReflectRoute: typeof ReflectRouteWithChildren
  SuttaRoute: typeof SuttaRouteWithChildren
  TreeRoute: typeof TreeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tree': {
      id: '/tree'
      path: '/tree'
      fullPath: '/tree'
      preLoaderRoute: typeof TreeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sutta': {
      id: '/sutta'
      path: '/sutta'
      fullPath: '/sutta'
      preLoaderRoute: typeof SuttaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reflect': {
      id: '/reflect'
      path: '/reflect'
      fullPath: '/reflect'
      preLoaderRoute: typeof ReflectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comic': {
      id: '/comic'
      path: '/comic'
      fullPath: '/comic'
      preLoaderRoute: typeof ComicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sutta/$suttaId': {
      id: '/sutta/$suttaId'
      path: '/$suttaId'
      fullPath: '/sutta/$suttaId'
      preLoaderRoute: typeof SuttaSuttaIdRouteImport
      parentRoute: typeof SuttaRoute
    }
    '/reflect/thinking': {
      id: '/reflect/thinking'
      path: '/thinking'
      fullPath: '/reflect/thinking'
      preLoaderRoute: typeof ReflectThinkingRouteImport
      parentRoute: typeof ReflectRoute
    }
    '/reflect/answer': {
      id: '/reflect/answer'
      path: '/answer'
      fullPath: '/reflect/answer'
      preLoaderRoute: typeof ReflectAnswerRouteImport
      parentRoute: typeof ReflectRoute
    }
  }
}

interface ReflectRouteChildren {
  ReflectAnswerRoute: typeof ReflectAnswerRoute
  ReflectThinkingRoute: typeof ReflectThinkingRoute
}

const ReflectRouteChildren: ReflectRouteChildren = {
  ReflectAnswerRoute: ReflectAnswerRoute,
  ReflectThinkingRoute: ReflectThinkingRoute,
}

const ReflectRouteWithChildren =
  ReflectRoute._addFileChildren(ReflectRouteChildren)

interface SuttaRouteChildren {
  SuttaSuttaIdRoute: typeof SuttaSuttaIdRoute
}

const SuttaRouteChildren: SuttaRouteChildren = {
  SuttaSuttaIdRoute: SuttaSuttaIdRoute,
}

const SuttaRouteWithChildren = SuttaRoute._addFileChildren(SuttaRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrowseRoute: BrowseRoute,
  ComicRoute: ComicRoute,
  ProfileRoute: ProfileRoute,
  ReflectRoute: ReflectRouteWithChildren,
  SuttaRoute: SuttaRouteWithChildren,
  TreeRoute: TreeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
